services:
  ddns-updater:
    image: qmcgaw/ddns-updater:v2.9.0
    container_name: ddns-updater
    network_mode: bridge
    ports:
      - 8001:8001/tcp
    volumes:
      - ddns-updater_data:/updater/data
    environment:
      - CONFIG=${CONFIG}
      - PERIOD=5m
      - UPDATE_COOLDOWN_PERIOD=5m
      - PUBLICIP_FETCHERS=all
      - PUBLICIP_HTTP_PROVIDERS=all
      - PUBLICIPV4_HTTP_PROVIDERS=all
      - PUBLICIPV6_HTTP_PROVIDERS=all
      - PUBLICIP_DNS_PROVIDERS=all
      - PUBLICIP_DNS_TIMEOUT=3s
      - HTTP_TIMEOUT=10s
      - RESOLVER_ADDRESS=1.1.1.1:53

      # Web UI
      - LISTENING_ADDRESS=:8001
      - ROOT_URL=/

      # Backup
      - BACKUP_PERIOD=0 # 0 to disable
      - BACKUP_DIRECTORY=/updater/data

      # Other
      - LOG_LEVEL=info
      - LOG_CALLER=hidden
      - SHOUTRRR_ADDRESSES=
    restart: always

volumes:
  ddns-updater_data:
    name: ddns-updater_data