services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.0.5
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - prowlarr_data:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.4.2
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - LANG=en_US
      - TZ=America/Chicago
    restart: unless-stopped

volumes:
  prowlarr_data:
    name: prowlarr_data