services:
  ombi:
    image: ghcr.io/linuxserver/ombi:development
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ombi_data:/config
    ports:
      - 3579:3579
    restart: unless-stopped

volumes:
  ombi_data:
    name: ombi_data