services:

  watchtower:
    #test
    image: containrrr/watchtower:latest
    container_name: watchtower
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    hostname: watchtower
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
      - WATCHTOWER_SCHEDULE=0 0 6 * * *
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_TIMEOUT=30s
      - WATCHTOWER_DEBUG=false
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_ROLLING_RESTART=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock