services:
  homebridge:
    image: homebridge/homebridge:latest
    restart: always
    network_mode: host
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    volumes:
      - homebridge_data:/homebridge
    environment:
      - TZ=America/Chicago
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '1'
    healthcheck:
      test: curl --fail localhost:8581 || exit 1
      interval: 60s
      retries: 5
      start_period: 300s
      timeout: 2s

volumes:
  homebridge_data:
    name: homebridge_data